/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Azores Open API
 * OpenAPI spec version: 2.0.0
 */
import {
  Hono
} from 'hono'
import { cors } from 'hono/cors'

import { apiKeyServiceListApiKeysHandlers } from './handlers/apiKeyServiceListApiKeys';
import { apiKeyServiceCreateApiKeyHandlers } from './handlers/apiKeyServiceCreateApiKey';
import { apiKeyServiceDeleteApiKeyHandlers } from './handlers/apiKeyServiceDeleteApiKey';
import { metricsServiceGetClusterMetricDataHandlers } from './handlers/metricsServiceGetClusterMetricData';
import { metricsServiceGetClusterMetricInstanceHandlers } from './handlers/metricsServiceGetClusterMetricInstance';
import { clusterServiceGetProcessListHandlers } from './handlers/clusterServiceGetProcessList';
import { clusterServiceDeleteProcessHandlers } from './handlers/clusterServiceDeleteProcess';
import { metricsServiceGetHostMetricDataHandlers } from './handlers/metricsServiceGetHostMetricData';
import { userServiceLoginHandlers } from './handlers/userServiceLogin';
import { userServiceLogoutHandlers } from './handlers/userServiceLogout';
import { metricsServiceGetMetricsHandlers } from './handlers/metricsServiceGetMetrics';
import { metricsServiceGetTopMetricDataHandlers } from './handlers/metricsServiceGetTopMetricData';
import { metricsServiceGetOverviewStatusHandlers } from './handlers/metricsServiceGetOverviewStatus';
import { roleServiceListRolesHandlers } from './handlers/roleServiceListRoles';
import { roleServiceCreateRoleHandlers } from './handlers/roleServiceCreateRole';
import { roleServiceDeleteRoleHandlers } from './handlers/roleServiceDeleteRole';
import { userServiceListUsersHandlers } from './handlers/userServiceListUsers';
import { userServiceCreateUserHandlers } from './handlers/userServiceCreateUser';
import { userServiceDeleteUserHandlers } from './handlers/userServiceDeleteUser';
import { userServiceUpdateUserHandlers } from './handlers/userServiceUpdateUser';
import { userServiceValidateSessionHandlers } from './handlers/userServiceValidateSession';


const app = new Hono()

app.use('/api/v2/*', cors())

/**
 * @summary ListApiKeys
 */

app.get('/api/v2/apiKeys', ...apiKeyServiceListApiKeysHandlers)


/**
 * @summary CreateApiKey
 */

app.post('/api/v2/apiKeys', ...apiKeyServiceCreateApiKeyHandlers)


/**
 * @summary deleteUser one user by user_id
 */

app.delete('/api/v2/apiKeys/:accessKey', ...apiKeyServiceDeleteApiKeyHandlers)


/**
 * @summary Get cluster metric data
 */

app.get('/api/v2/clusters/:clusterId/metrics/:name/data', ...metricsServiceGetClusterMetricDataHandlers)


/**
 * @summary Get metric instances
 */

app.get('/api/v2/clusters/:clusterId/metrics/:name/instance', ...metricsServiceGetClusterMetricInstanceHandlers)


/**
 * @summary GetProcessList retrieves the list of running processes in a cluster
 */

app.get('/api/v2/clusters/:clusterId/sessions', ...clusterServiceGetProcessListHandlers)


/**
 * @summary DeleteProcess terminates a specific process in the cluster
 */

app.delete('/api/v2/clusters/:clusterId/sessions/:sessionId', ...clusterServiceDeleteProcessHandlers)


/**
 * @summary Get host metric data
 */

app.get('/api/v2/hosts/:hostId/metrics/:name/data', ...metricsServiceGetHostMetricDataHandlers)


/**
 * @summary login
 */

app.post('/api/v2/login', ...userServiceLoginHandlers)


/**
 * @summary Logout
 */

app.post('/api/v2/logout', ...userServiceLogoutHandlers)


/**
 * @summary Get metrics info
 */

app.get('/api/v2/metrics', ...metricsServiceGetMetricsHandlers)


/**
 * @summary Get top metric data
 */

app.get('/api/v2/overview/metrics/:name/data', ...metricsServiceGetTopMetricDataHandlers)


/**
 * @summary Get overview status
 */

app.get('/api/v2/overview/status', ...metricsServiceGetOverviewStatusHandlers)


/**
 * @summary listRoles
 */

app.get('/api/v2/roles', ...roleServiceListRolesHandlers)


/**
 * @summary createRole
 */

app.post('/api/v2/roles', ...roleServiceCreateRoleHandlers)


/**
 * @summary deleteUser one user by user_id
 */

app.delete('/api/v2/roles/:roleId', ...roleServiceDeleteRoleHandlers)


/**
 * @summary ListUsers
 */

app.get('/api/v2/users', ...userServiceListUsersHandlers)


/**
 * @summary createUser
 */

app.post('/api/v2/users', ...userServiceCreateUserHandlers)


/**
 * @summary delete one user by user_id
 */

app.delete('/api/v2/users/:userId', ...userServiceDeleteUserHandlers)


/**
 * @summary Update User
 */

app.patch('/api/v2/users/:userId', ...userServiceUpdateUserHandlers)


/**
 * @summary ValidateSession
 */

app.get('/api/v2/users:validateSession', ...userServiceValidateSessionHandlers)


export default app