// Copyright 2022 PingCAP, Inc. Licensed under Apache-2.0.

package profutil

import (
	"io/ioutil"
	"regexp"
	"testing"

	"github.com/stretchr/testify/require"
)

func Test_convertProtoToDot(t *testing.T) {
	proto, err := ioutil.ReadFile("testdata/sample_cpu.proto")
	require.NoError(t, err)

	dot, err := convertProtoToDot(proto)
	require.NoError(t, err)

	expectedDot, err := ioutil.ReadFile("testdata/sample_cpu.dot")
	require.NoError(t, err)

	require.Equal(t, expectedDot, dot)
}

func TestConvertProtoToGraphSVG(t *testing.T) {
	proto, err := ioutil.ReadFile("testdata/sample_cpu.proto")
	require.NoError(t, err)

	svg, err := ConvertProtoToGraphSVG(proto)
	require.NoError(t, err)

	expectedSvg, err := ioutil.ReadFile("testdata/sample_cpu.svg")
	require.NoError(t, err)

	r := regexp.MustCompile(`Generated by graphviz version [\d\.]+ \([\d\.]+\)`)
	svgWithoutVer := r.ReplaceAllString(string(svg), "_")
	expectedSvgWithoutVer := r.ReplaceAllString(string(expectedSvg), "_")

	require.Equal(t, expectedSvgWithoutVer, svgWithoutVer)
}
