// Code generated by "stringer -type=Operation"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpListTargets-0]
	_ = x[OpStartBundle-1]
	_ = x[OpListBundles-2]
	_ = x[OpGetBundle-3]
	_ = x[OpGetProfileData-4]
	_ = x[OpGetBundleData-5]
}

const _Operation_name = "OpListTargetsOpStartBundleOpListBundlesOpGetBundleOpGetProfileDataOpGetBundleData"

var _Operation_index = [...]uint8{0, 13, 26, 39, 50, 66, 81}

func (i Operation) String() string {
	if i < 0 || i >= Operation(len(_Operation_index)-1) {
		return "Operation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Operation_name[_Operation_index[i]:_Operation_index[i+1]]
}
