run:
  skip-dirs:
    - swaggerspec
    - pkg/uiserver
    - ui
  timeout: 2m

issues:
  include:
    # Bring back all gosec checks
    - EXC0006
    - EXC0007
    - EXC0008
    - EXC0009
    - EXC0010
  exclude-rules:
    # TODO: Current code base does not work well for these linters. We should bring back one by one.
    - path: ^pkg/|^cmd/
      linters:
        - nestif
        - exhaustive
        - wastedassign
        - errorlint
    # https://github.com/open-telemetry/opentelemetry-collector/issues/5699
    - text: "G112:"
      linters:
        - gosec

linters:
  enable:
    # Additionally enable some checkers
    - asciicheck
    - depguard
    - dogsled
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - godot
    - gofumpt
    - goheader
    - goimports
    - gosec
    - importas
    - nestif
    - prealloc
    - predeclared
    - revive
    - unconvert
    - whitespace

linters-settings:
  goimports:
    local-prefixes: github.com/pingcap/tidb-dashboard
  exhaustive:
    # only cover the case when default is not given
    default-signifies-exhaustive: true
  godot:
    # exclude swag annotations
    exclude:
      - "^\\s*@"
  goheader:
    template: |-
      Copyright {{ YEAR }} PingCAP, Inc. Licensed under Apache-2.0.
