version: "2"
linters:
  enable:
    - asciicheck
    - dogsled
    - durationcheck
    - errorlint
    - exhaustive
    - godot
    - goheader
    - gosec
    - importas
    - misspell
    - nestif
    - prealloc
    - predeclared
    - revive
    - unconvert
    - whitespace
  settings:
    exhaustive:
      default-signifies-exhaustive: true
    godot:
      exclude:
        - ^\s*@
    goheader:
      template: Copyright {{ YEAR }} PingCAP, Inc. Licensed under Apache-2.0.
    revive:
      rules:
        - name: var-naming
          severity: warning
          disabled: false
          exclude: [""]
          arguments:
            - [ "utils" ] # AllowList
            - [ "VM" ] # DenyList
            - - skip-package-name-checks: true
    gosec:
      excludes:
        - G115 # Type conversion which leads to integer overflow
  exclusions:
    generated: lax
    presets:
      - comments
      - std-error-handling
    rules:
      - path: ^pkg/|^cmd/
        linters:
          - errorlint
          - exhaustive
          - nestif
          - wastedassign
      - path: _test.go
        linters:
          - gosec
        test: "G705"
    paths:
      - swaggerspec
      - pkg/uiserver
      - ui
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/pingcap/tidb-dashboard
  exclusions:
    generated: lax
    paths:
      - swaggerspec
      - pkg/uiserver
      - ui
      - third_party$
      - builtin$
      - examples$
