version: "2"
linters:
  enable:
    - asciicheck
    - dogsled
    - durationcheck
    - errorlint
    - exhaustive
    - godot
    - goheader
    - gosec
    - importas
    - nestif
    - prealloc
    - predeclared
    - revive
    - unconvert
    - whitespace
<<<<<<< HEAD

linters-settings:
  goimports:
    local-prefixes: github.com/pingcap/tidb-dashboard
  exhaustive:
    # only cover the case when default is not given
    default-signifies-exhaustive: true
  godot:
    # exclude swag annotations
    exclude:
      - "^\\s*@"
=======
  settings:
    exhaustive:
      default-signifies-exhaustive: true
    godot:
      exclude:
        - ^\s*@
    goheader:
      template: Copyright {{ YEAR }} PingCAP, Inc. Licensed under Apache-2.0.
    revive:
      rules:
        - name: var-naming
          severity: warning
          disabled: false
          exclude: [""]
          arguments:
            - [ "utils" ] # AllowList
            - [ "VM" ] # DenyList
            - - skip-package-name-checks: true
  exclusions:
    generated: lax
    presets:
      - comments
      - std-error-handling
    rules:
      - linters:
          - errorlint
          - exhaustive
          - nestif
          - wastedassign
        path: ^pkg/|^cmd/
      - linters:
          - gosec
        text: 'G112:'
      - linters:
          - gosec
        text: G115
    paths:
      - swaggerspec
      - pkg/uiserver
      - ui
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/pingcap/tidb-dashboard
  exclusions:
    generated: lax
    paths:
      - swaggerspec
      - pkg/uiserver
      - ui
      - third_party$
      - builtin$
      - examples$
>>>>>>> 855b2ffdf (Update go version to 1.25 (#1839))
