version: 2

jobs:
  build:
    docker:
      - image: golang:1.13
    working_directory: /go/src/github.com/pingcap/pd
    environment:
      GOFLAGS: -p=8
    steps:
      - checkout
      - restore_cache:
          name: "Restore Build Cache"
          key: go-build-v1-{{ checksum "go.mod" }}-{{ checksum "go.sum" }}
      - restore_cache:
          name: "Restore Tools"
          key: tools-v1-{{ checksum "tools.json" }}
      - run:
          name: "Build & Test"
          command: make ci
      - save_cache:
          name: "Save Build Cache"
          key: go-build-v1-{{ checksum "go.mod" }}-{{ checksum "go.sum" }}
          paths:
            - /root/.cache/go-build
            - /go/pkg/mod
      - save_cache:
          name: "Save Tools"
          key: tools-v1-{{ checksum "tools.json" }}
          paths:
            - .retools
