/* tslint:disable */
/* eslint-disable */
/**
 * Dashboard API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ConprofTarget } from './conprof-target';

/**
 * 
 * @export
 * @interface ConprofProfileDetail
 */
export interface ConprofProfileDetail {
    /**
     * 
     * @type {string}
     * @memberof ConprofProfileDetail
     */
    'error'?: string;
    /**
     * 
     * @type {string}
     * @memberof ConprofProfileDetail
     */
    'profile_type'?: string;
    /**
     * 
     * @type {string}
     * @memberof ConprofProfileDetail
     */
    'state'?: string;
    /**
     * 
     * @type {ConprofTarget}
     * @memberof ConprofProfileDetail
     */
    'target'?: ConprofTarget;
}

