/* tslint:disable */
/* eslint-disable */
/**
 * Dashboard API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DiagnoseGenDiagnosisReportRequest
 */
export interface DiagnoseGenDiagnosisReportRequest {
    /**
     * 
     * @type {number}
     * @memberof DiagnoseGenDiagnosisReportRequest
     */
    'end_time'?: number;
    /**
     * values: config, error, performance
     * @type {string}
     * @memberof DiagnoseGenDiagnosisReportRequest
     */
    'kind'?: string;
    /**
     * 
     * @type {number}
     * @memberof DiagnoseGenDiagnosisReportRequest
     */
    'start_time'?: number;
}

