/* tslint:disable */
/* eslint-disable */
/**
 * Dashboard API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SsoSSOImpersonationModel
 */
export interface SsoSSOImpersonationModel {
    /**
     * 
     * @type {string}
     * @memberof SsoSSOImpersonationModel
     */
    'last_impersonate_status'?: string;
    /**
     * 
     * @type {string}
     * @memberof SsoSSOImpersonationModel
     */
    'sql_user'?: string;
}

