// Code generated by mockery v2.9.4. DO NOT EDIT.

package topo

import mock "github.com/stretchr/testify/mock"

// MockInfo is an autogenerated mock type for the Info type
type MockInfo struct {
	mock.Mock
}

// Describe provides a mock function with given fields:
func (_m *MockInfo) Describe() ComponentDescriptor {
	ret := _m.Called()

	var r0 ComponentDescriptor
	if rf, ok := ret.Get(0).(func() ComponentDescriptor); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(ComponentDescriptor)
	}

	return r0
}
