/* tslint:disable */
/* eslint-disable */
/**
 * Dashboard API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ConprofComponentNum
 */
export interface ConprofComponentNum {
    /**
     * 
     * @type {number}
     * @memberof ConprofComponentNum
     */
    'pd'?: number;
    /**
     * 
     * @type {number}
     * @memberof ConprofComponentNum
     */
    'ticdc'?: number;
    /**
     * 
     * @type {number}
     * @memberof ConprofComponentNum
     */
    'tidb'?: number;
    /**
     * 
     * @type {number}
     * @memberof ConprofComponentNum
     */
    'tiflash'?: number;
    /**
     * 
     * @type {number}
     * @memberof ConprofComponentNum
     */
    'tikv'?: number;
}

