/* tslint:disable */
/* eslint-disable */
/**
 * Dashboard API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EndpointAPIParamDefinition
 */
export interface EndpointAPIParamDefinition {
    /**
     * 
     * @type {string}
     * @memberof EndpointAPIParamDefinition
     */
    'name'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof EndpointAPIParamDefinition
     */
    'required'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof EndpointAPIParamDefinition
     */
    'ui_kind'?: string;
    /**
     * varies by different ui kinds
     * @type {object}
     * @memberof EndpointAPIParamDefinition
     */
    'ui_props'?: object;
}

