/* tslint:disable */
/* eslint-disable */
/**
 * Dashboard API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { EndpointAPIParamDefinition } from './endpoint-apiparam-definition';

/**
 * 
 * @export
 * @interface EndpointAPIDefinition
 */
export interface EndpointAPIDefinition {
    /**
     * 
     * @type {string}
     * @memberof EndpointAPIDefinition
     */
    'component'?: string;
    /**
     * 
     * @type {string}
     * @memberof EndpointAPIDefinition
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof EndpointAPIDefinition
     */
    'method'?: string;
    /**
     * 
     * @type {string}
     * @memberof EndpointAPIDefinition
     */
    'path'?: string;
    /**
     * e.g. /stats/dump/{db}/{table} -> db, table
     * @type {Array<EndpointAPIParamDefinition>}
     * @memberof EndpointAPIDefinition
     */
    'path_params'?: Array<EndpointAPIParamDefinition>;
    /**
     * e.g. /debug/pprof?seconds=1 -> seconds
     * @type {Array<EndpointAPIParamDefinition>}
     * @memberof EndpointAPIDefinition
     */
    'query_params'?: Array<EndpointAPIParamDefinition>;
}

