/* tslint:disable */
/* eslint-disable */
/**
 * Dashboard API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { VersionInfo } from './version-info';

/**
 * 
 * @export
 * @interface InfoInfoResponse
 */
export interface InfoInfoResponse {
    /**
     * 
     * @type {boolean}
     * @memberof InfoInfoResponse
     */
    'enable_experimental'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof InfoInfoResponse
     */
    'enable_telemetry'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof InfoInfoResponse
     */
    'ngm_state'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof InfoInfoResponse
     */
    'supported_features'?: Array<string>;
    /**
     * 
     * @type {VersionInfo}
     * @memberof InfoInfoResponse
     */
    'version'?: VersionInfo;
}

