/* tslint:disable */
/* eslint-disable */
/**
 * Dashboard API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { MaterializedviewRefreshAlertItem } from './materializedview-refresh-alert-item';

/**
 * 
 * @export
 * @interface MaterializedviewRefreshAlertResponse
 */
export interface MaterializedviewRefreshAlertResponse {
    /**
     * 
     * @type {Array<MaterializedviewRefreshAlertItem>}
     * @memberof MaterializedviewRefreshAlertResponse
     */
    'items'?: Array<MaterializedviewRefreshAlertItem>;
    /**
     * 
     * @type {number}
     * @memberof MaterializedviewRefreshAlertResponse
     */
    'total'?: number;
}

