/* tslint:disable */
/* eslint-disable */
/**
 * Dashboard API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ResourcemanagerResourceInfoRowDef
 */
export interface ResourcemanagerResourceInfoRowDef {
    /**
     * 
     * @type {string}
     * @memberof ResourcemanagerResourceInfoRowDef
     */
    'burstable'?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourcemanagerResourceInfoRowDef
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourcemanagerResourceInfoRowDef
     */
    'priority'?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourcemanagerResourceInfoRowDef
     */
    'ru_per_sec'?: string;
}

