/* tslint:disable */
/* eslint-disable */
/**
 * Dashboard API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface StatementGetStatementsRequest
 */
export interface StatementGetStatementsRequest {
    /**
     * 
     * @type {number}
     * @memberof StatementGetStatementsRequest
     */
    'begin_time'?: number;
    /**
     * 
     * @type {number}
     * @memberof StatementGetStatementsRequest
     */
    'end_time'?: number;
    /**
     * 
     * @type {string}
     * @memberof StatementGetStatementsRequest
     */
    'fields'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof StatementGetStatementsRequest
     */
    'resource_groups'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof StatementGetStatementsRequest
     */
    'schemas'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof StatementGetStatementsRequest
     */
    'stmt_types'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof StatementGetStatementsRequest
     */
    'text'?: string;
}

