/* tslint:disable */
/* eslint-disable */
/**
 * Dashboard API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { TopologyStoreLabels } from './topology-store-labels';

/**
 * 
 * @export
 * @interface TopologyStoreLocation
 */
export interface TopologyStoreLocation {
    /**
     * 
     * @type {Array<string>}
     * @memberof TopologyStoreLocation
     */
    'location_labels'?: Array<string>;
    /**
     * 
     * @type {Array<TopologyStoreLabels>}
     * @memberof TopologyStoreLocation
     */
    'stores'?: Array<TopologyStoreLabels>;
}

