/* tslint:disable */
/* eslint-disable */
/**
 * Dashboard API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TopsqlSummaryPlanItem
 */
export interface TopsqlSummaryPlanItem {
    /**
     * 
     * @type {Array<number>}
     * @memberof TopsqlSummaryPlanItem
     */
    'cpu_time_ms'?: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof TopsqlSummaryPlanItem
     */
    'duration_per_exec_ms'?: number;
    /**
     * 
     * @type {number}
     * @memberof TopsqlSummaryPlanItem
     */
    'exec_count_per_sec'?: number;
    /**
     * 
     * @type {string}
     * @memberof TopsqlSummaryPlanItem
     */
    'plan_digest'?: string;
    /**
     * 
     * @type {string}
     * @memberof TopsqlSummaryPlanItem
     */
    'plan_text'?: string;
    /**
     * 
     * @type {number}
     * @memberof TopsqlSummaryPlanItem
     */
    'scan_indexes_per_sec'?: number;
    /**
     * 
     * @type {number}
     * @memberof TopsqlSummaryPlanItem
     */
    'scan_records_per_sec'?: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof TopsqlSummaryPlanItem
     */
    'timestamp_sec'?: Array<number>;
}

