/* tslint:disable */
/* eslint-disable */
/**
 * Dashboard API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TopsqlSummaryByItem
 */
export interface TopsqlSummaryByItem {
    /**
     * 
     * @type {Array<number>}
     * @memberof TopsqlSummaryByItem
     */
    'cpu_time_ms'?: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof TopsqlSummaryByItem
     */
    'cpu_time_ms_sum'?: number;
    /**
     * 
     * @type {string}
     * @memberof TopsqlSummaryByItem
     */
    'text'?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof TopsqlSummaryByItem
     */
    'timestamp_sec'?: Array<number>;
}

