/* tslint:disable */
/* eslint-disable */
/**
 * Dashboard API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { TopsqlSummaryByItem } from './topsql-summary-by-item';
import { TopsqlSummaryItem } from './topsql-summary-item';

/**
 * 
 * @export
 * @interface TopsqlSummaryResponse
 */
export interface TopsqlSummaryResponse {
    /**
     * 
     * @type {Array<TopsqlSummaryItem>}
     * @memberof TopsqlSummaryResponse
     */
    'data'?: Array<TopsqlSummaryItem>;
    /**
     * 
     * @type {Array<TopsqlSummaryByItem>}
     * @memberof TopsqlSummaryResponse
     */
    'data_by'?: Array<TopsqlSummaryByItem>;
}

