/* tslint:disable */
/* eslint-disable */
/**
 * Dashboard API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { TopsqlSummaryPlanItem } from './topsql-summary-plan-item';

/**
 * 
 * @export
 * @interface TopsqlSummaryItem
 */
export interface TopsqlSummaryItem {
    /**
     * 
     * @type {number}
     * @memberof TopsqlSummaryItem
     */
    'cpu_time_ms'?: number;
    /**
     * 
     * @type {number}
     * @memberof TopsqlSummaryItem
     */
    'duration_per_exec_ms'?: number;
    /**
     * 
     * @type {number}
     * @memberof TopsqlSummaryItem
     */
    'exec_count_per_sec'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof TopsqlSummaryItem
     */
    'is_other'?: boolean;
    /**
     * 
     * @type {Array<TopsqlSummaryPlanItem>}
     * @memberof TopsqlSummaryItem
     */
    'plans'?: Array<TopsqlSummaryPlanItem>;
    /**
     * 
     * @type {number}
     * @memberof TopsqlSummaryItem
     */
    'scan_indexes_per_sec'?: number;
    /**
     * 
     * @type {number}
     * @memberof TopsqlSummaryItem
     */
    'scan_records_per_sec'?: number;
    /**
     * 
     * @type {string}
     * @memberof TopsqlSummaryItem
     */
    'sql_digest'?: string;
    /**
     * 
     * @type {string}
     * @memberof TopsqlSummaryItem
     */
    'sql_text'?: string;
}

