/* tslint:disable */
/* eslint-disable */
/**
 * Dashboard API
 * No description provided (generated by Openapi Generator https://github.com/OpenAPITools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TopsqlUpdateTikvNetworkIoCollectionRequest
 */
export interface TopsqlUpdateTikvNetworkIoCollectionRequest {
    /**
     *
     * @type {boolean}
     * @memberof TopsqlUpdateTikvNetworkIoCollectionRequest
     */
    'detailed_io_enabled'?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof TopsqlUpdateTikvNetworkIoCollectionRequest
     */
    'enable': boolean;
}
