/* tslint:disable */
/* eslint-disable */
/**
 * Dashboard API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserGetLoginInfoResponse
 */
export interface UserGetLoginInfoResponse {
    /**
     * 
     * @type {string}
     * @memberof UserGetLoginInfoResponse
     */
    'sql_auth_public_key'?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof UserGetLoginInfoResponse
     */
    'supported_auth_types'?: Array<number>;
}

