export interface SlowqueryModel {
  backoff_time?: number
  backoff_types?: string
  binary_plan?: string
  binary_plan_json?: string
  binary_plan_text?: string
  commit_backoff_time?: number
  commit_time?: number
  compile_time?: number
  connection_id?: string
  cop_proc_addr?: string
  cop_proc_avg?: number
  cop_proc_max?: number
  cop_proc_p90?: number
  cop_time?: number
  cop_wait_addr?: string
  cop_wait_avg?: number
  cop_wait_max?: number
  cop_wait_p90?: number
  db?: string
  digest?: string
  disk_max?: number
  exec_retry_time?: number
  get_commit_ts_time?: number
  host?: string
  index_names?: string
  instance?: string
  is_internal?: number
  local_latch_wait_time?: number
  lock_keys_time?: number
  memory_max?: number
  optimize_time?: number
  parse_time?: number
  plan?: string
  plan_from_binding?: number
  plan_from_cache?: number
  prepared?: number
  preproc_subqueries_time?: number
  prev_stmt?: string
  prewrite_region?: number
  prewrite_time?: number
  process_keys?: number
  process_time?: number
  query?: string
  query_time?: number
  request_count?: number
  resolve_lock_time?: number
  resource_group?: string
  rewrite_time?: number
  rocksdb_block_cache_hit_count?: number
  rocksdb_block_read_byte?: number
  rocksdb_block_read_count?: number
  rocksdb_delete_skipped_count?: number
  rocksdb_key_skipped_count?: number
  ru?: number
  stats?: string
  success?: number
  time_queued_by_rc?: number
  timestamp?: number
  total_keys?: number
  txn_retry?: number
  txn_start_ts?: string
  user?: string
  wait_prewrite_binlog_time?: number
  wait_time?: number
  wait_ts?: number
  warnings?: string | object[]
  write_keys?: number
  write_size?: number
  write_sql_response_total?: number
}
