/* tslint:disable */
/* eslint-disable */
/**
 * Dashboard API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ConprofComponentNum } from './conprof-component-num';

/**
 * 
 * @export
 * @interface ConprofGroupProfiles
 */
export interface ConprofGroupProfiles {
    /**
     * 
     * @type {ConprofComponentNum}
     * @memberof ConprofGroupProfiles
     */
    'component_num'?: ConprofComponentNum;
    /**
     * 
     * @type {number}
     * @memberof ConprofGroupProfiles
     */
    'profile_duration_secs'?: number;
    /**
     * 
     * @type {string}
     * @memberof ConprofGroupProfiles
     */
    'state'?: string;
    /**
     * 
     * @type {number}
     * @memberof ConprofGroupProfiles
     */
    'ts'?: number;
}

