/* tslint:disable */
/* eslint-disable */
/**
 * Dashboard API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TopologyTiDBInfo
 */
export interface TopologyTiDBInfo {
    /**
     * 
     * @type {string}
     * @memberof TopologyTiDBInfo
     */
    'deploy_path'?: string;
    /**
     * 
     * @type {string}
     * @memberof TopologyTiDBInfo
     */
    'git_hash'?: string;
    /**
     * 
     * @type {string}
     * @memberof TopologyTiDBInfo
     */
    'ip'?: string;
    /**
     * 
     * @type {number}
     * @memberof TopologyTiDBInfo
     */
    'port'?: number;
    /**
     * 
     * @type {number}
     * @memberof TopologyTiDBInfo
     */
    'start_timestamp'?: number;
    /**
     * 
     * @type {number}
     * @memberof TopologyTiDBInfo
     */
    'status'?: number;
    /**
     * 
     * @type {number}
     * @memberof TopologyTiDBInfo
     */
    'status_port'?: number;
    /**
     * 
     * @type {string}
     * @memberof TopologyTiDBInfo
     */
    'version'?: string;
}

