/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Example API
 * This is a Clinic server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export * from './api/api-key-api';
export * from './api/cluster-api';
export * from './api/health-report-api';
export * from './api/oauth-api';
export * from './api/organization-api';
export * from './api/report-api';
export * from './api/upload-api';
export * from './api/user-api';

