const vpData = {
  main: {
    accessObject: {
      dynamicpartitionObjects: null,
      otherObject: null,
      scanObject: null,
    },
    actRows: '1',
    children: [
      {
        accessObject: {
          dynamicpartitionObjects: null,
          otherObject: null,
          scanObject: null,
        },
        actRows: '1',
        children: [
          {
            accessObject: {
              dynamicpartitionObjects: null,
              otherObject: null,
              scanObject: null,
            },
            actRows: '1',
            children: [
              {
                accessObject: {
                  dynamicpartitionObjects: null,
                  otherObject: null,
                  scanObject: null,
                },
                children: [
                  {
                    accessObject: {
                      dynamicpartitionObjects: null,
                      otherObject: null,
                      scanObject: {
                        database: 'INFORMATION_SCHEMA',
                        table: 'CLUSTER_SLOW_QUERY',
                      },
                    },
                    copExecInfo: {},
                    cost: 999,
                    diagnosis: [],
                    diskBytes: 'N/A',
                    duration: '0s',
                    estRows: 1,
                    memoryBytes: 'N/A',
                    name: 'TableRangeScan_1dsf9',
                    operatorInfo:
                      'range:[2022-07-06 20:10:21.726562,2022-07-06 20:10:21.726562], keep order:false, stats:pseudo',
                    rootBasicExecInfo: {},
                    rootGroupExecInfo: [],
                    storeType: 'tidb',
                    taskType: 'cop',
                    children: [
                      {
                        actRows: '1',
                        copExecInfo: {},
                        diagnosis: [],
                        diskBytes: 'N/A',
                        duration: '564ns',
                        estRows: 1,
                        memoryBytes: 'N/A',
                        name: 'sdfsdfTableDuadfl_12',
                        operatorInfo: 'rows:1',
                        rootBasicExecInfo: {
                          loops: '2',
                          time: '564ns',
                        },
                        rootGroupExecInfo: [],
                        storeType: 'tidb',
                        taskType: 'root',
                        children: [
                          {
                            actRows: '1',
                            copExecInfo: {},
                            diagnosis: [],
                            diskBytes: 'N/A',
                            duration: '564ns',
                            estRows: 1,
                            memoryBytes: 'N/A',
                            name: 'TasdfbleDuadfl_12',
                            operatorInfo: 'rows:1',
                            rootBasicExecInfo: {
                              loops: '2',
                              time: '564ns',
                            },
                            rootGroupExecInfo: [],
                            storeType: 'tidb',
                            taskType: 'root',
                            children: [
                              {
                                actRows: '1',
                                copExecInfo: {},
                                diagnosis: [],
                                diskBytes: 'N/A',
                                duration: '564ns',
                                estRows: 1,
                                memoryBytes: 'N/A',
                                name: 'TableDsdfuadfl_12',
                                operatorInfo: 'rows:1',
                                rootBasicExecInfo: {
                                  loops: '2',
                                  time: '564ns',
                                },
                                rootGroupExecInfo: [],
                                storeType: 'tidb',
                                taskType: 'root',
                              },
                            ],
                          },
                        ],
                      },
                    ],
                  },
                ],
                copExecInfo: {},
                cost: 1002,
                diagnosis: [],
                diskBytes: 'N/A',
                duration: '0s',
                estRows: 0.00001,
                memoryBytes: 'N/A',
                name: 'Selection_20',
                operatorInfo:
                  'eq(information_schema.cluster_slow_query.conn_id, 7105277235153601571), eq(information_schema.cluster_slow_query.digest, "aa03ae0c8abec8ff2ed3dba6ba97d916527ab94136c2f5846d73cb03a310230b")',
                rootBasicExecInfo: {},
                rootGroupExecInfo: [],
                storeType: 'tidb',
                taskType: 'cop',
              },
            ],
            copExecInfo: {},
            cost: 66.80040083333333,
            diagnosis: [],
            diskBytes: 'N/A',
            duration: '41.9ms',
            estRows: 0.00001,
            memoryBytes: '29224',
            name: 'TableReader_21',
            operatorInfo: 'data:Selection_20',
            rootBasicExecInfo: {
              loops: '2',
              time: '41.9ms',
            },
            rootGroupExecInfo: [
              {
                cop_task: {
                  copr_cache_hit_ratio: '0.00',
                  distsql_concurrency: '15',
                  max: '41.8ms',
                  num: '1',
                  proc_keys: '0',
                  rpc_num: '1',
                  rpc_time: '41.8ms',
                },
              },
            ],
            storeType: 'tidb',
            taskType: 'root',
          },
        ],
        copExecInfo: {},
        cost: 66.80243083333333,
        diagnosis: [],
        diskBytes: 'N/A',
        duration: '42ms',
        estRows: 0.00001,
        memoryBytes: '37834',
        name: 'TopN_10',
        operatorInfo:
          'information_schema.cluster_slow_query.digest, offset:0, count:1',
        rootBasicExecInfo: {
          loops: '2',
          time: '42ms',
        },
        rootGroupExecInfo: [],
        storeType: 'tidb',
        taskType: 'root',
      },
    ],
    copExecInfo: {},
    cost: 84.80243683333333,
    diagnosis: [],
    diskBytes: 'N/A',
    duration: '42.2ms',
    estRows: 0.00001,
    memoryBytes: '61272',
    name: 'Projection_7',
    operatorInfo:
      'information_schema.cluster_slow_query.instance, information_schema.cluster_slow_query.time, information_schema.cluster_slow_query.txn_start_ts, information_schema.cluster_slow_query.user, information_schema.cluster_slow_query.host, information_schema.cluster_slow_query.conn_id, information_schema.cluster_slow_query.exec_retry_count, information_schema.cluster_slow_query.exec_retry_time, information_schema.cluster_slow_query.query_time, information_schema.cluster_slow_query.parse_time, information_schema.cluster_slow_query.compile_time, information_schema.cluster_slow_query.rewrite_time, information_schema.cluster_slow_query.preproc_subqueries, information_schema.cluster_slow_query.preproc_subqueries_time, information_schema.cluster_slow_query.optimize_time, information_schema.cluster_slow_query.wait_ts, information_schema.cluster_slow_query.prewrite_time, information_schema.cluster_slow_query.wait_prewrite_binlog_time, information_schema.cluster_slow_query.commit_time, information_schema.cluster_slow_query.get_commit_ts_time, information_schema.cluster_slow_query.commit_backoff_time, information_schema.cluster_slow_query.backoff_types, information_schema.cluster_slow_query.resolve_lock_time, information_schema.cluster_slow_query.local_latch_wait_time, information_schema.cluster_slow_query.write_keys, information_schema.cluster_slow_query.write_size, information_schema.cluster_slow_query.prewrite_region, information_schema.cluster_slow_query.txn_retry, information_schema.cluster_slow_query.cop_time, information_schema.cluster_slow_query.process_time, information_schema.cluster_slow_query.wait_time, information_schema.cluster_slow_query.backoff_time, information_schema.cluster_slow_query.lockkeys_time, information_schema.cluster_slow_query.request_count, information_schema.cluster_slow_query.total_keys, information_schema.cluster_slow_query.process_keys, information_schema.cluster_slow_query.rocksdb_delete_skipped_count, information_schema.cluster_slow_query.rocksdb_key_skipped_count, information_schema.cluster_slow_query.rocksdb_block_cache_hit_count, information_schema.cluster_slow_query.rocksdb_block_read_count, information_schema.cluster_slow_query.rocksdb_block_read_byte, information_schema.cluster_slow_query.db, information_schema.cluster_slow_query.index_names, information_schema.cluster_slow_query.is_internal, information_schema.cluster_slow_query.digest, information_schema.cluster_slow_query.stats, information_schema.cluster_slow_query.cop_proc_avg, information_schema.cluster_slow_query.cop_proc_p90, information_schema.cluster_slow_query.cop_proc_max, information_schema.cluster_slow_query.cop_proc_addr, information_schema.cluster_slow_query.cop_wait_avg, information_schema.cluster_slow_query.cop_wait_p90, information_schema.cluster_slow_query.cop_wait_max, information_schema.cluster_slow_query.cop_wait_addr, information_schema.cluster_slow_query.mem_max, information_schema.cluster_slow_query.disk_max, information_schema.cluster_slow_query.kv_total, information_schema.cluster_slow_query.pd_total, information_schema.cluster_slow_query.backoff_total, information_schema.cluster_slow_query.write_sql_response_total, information_schema.cluster_slow_query.result_rows, information_schema.cluster_slow_query.backoff_detail, information_schema.cluster_slow_query.prepared, information_schema.cluster_slow_query.succ, information_schema.cluster_slow_query.isexplicittxn, information_schema.cluster_slow_query.iswritecachetable, information_schema.cluster_slow_query.plan_from_cache, information_schema.cluster_slow_query.plan_from_binding, information_schema.cluster_slow_query.has_more_results, information_schema.cluster_slow_query.plan, information_schema.cluster_slow_query.plan_digest, information_schema.cluster_slow_query.binary_plan, information_schema.cluster_slow_query.prev_stmt, information_schema.cluster_slow_query.query, plus(cast(unix_timestamp(information_schema.cluster_slow_query.time), double BINARY), 0)->Column#75',
    rootBasicExecInfo: {
      loops: '2',
      time: '42.2ms',
    },
    rootGroupExecInfo: [
      {
        Concurrency: 'OFF',
      },
    ],
    storeType: 'tidb',
    taskType: 'root',
  },
  ctes: [
    {
      actRows: '1',
      children: [
        {
          actRows: '1',
          children: [
            {
              actRows: '1',
              copExecInfo: {},
              diagnosis: [],
              diskBytes: 'N/A',
              duration: '564ns',
              estRows: 1,
              memoryBytes: 'N/A',
              name: 'TableDual_12',
              operatorInfo: 'rows:1',
              rootBasicExecInfo: {
                loops: '2',
                time: '564ns',
              },
              rootGroupExecInfo: [],
              storeType: 'tidb',
              taskType: 'root',
            },
          ],
          copExecInfo: {},
          cost: 18.6,
          diagnosis: [],
          diskBytes: 'N/A',
          driverSide: 'seed',
          duration: '4.14µs',
          estRows: 1,
          name: 'Projection_11',
          operatorInfo: '1->Column#2',
          rootBasicExecInfo: {
            loops: '2',
            time: '4.14µs',
          },
          rootGroupExecInfo: [
            {
              Concurrency: 'OFF',
            },
          ],
          storeType: 'tidb',
          taskType: 'root',
        },
        {
          children: [
            {
              children: [
                {
                  actRows: '1',
                  copExecInfo: {},
                  diagnosis: [],
                  diskBytes: 'N/A',
                  duration: '7.18µs',
                  estRows: 1,
                  memoryBytes: 'N/A',
                  name: 'CTETable_15',
                  operatorInfo: 'Scan on CTE_0',
                  rootBasicExecInfo: {
                    loops: '2',
                    time: '7.18µs',
                  },
                  rootGroupExecInfo: [],
                  storeType: 'tidb',
                  taskType: 'root',
                },
              ],
              copExecInfo: {},
              cost: 3,
              diagnosis: [],
              diskBytes: 'N/A',
              duration: '1s',
              estRows: 0.8,
              memoryBytes: '380',
              name: 'Selection_14',
              operatorInfo: 'lt(Column#3, 5), sleep(1)',
              rootBasicExecInfo: {
                loops: '1',
                time: '1s',
              },
              rootGroupExecInfo: [],
              storeType: 'tidb',
              taskType: 'root',
            },
          ],
          copExecInfo: {},
          cost: 21.48,
          diagnosis: [],
          diskBytes: 'N/A',
          driverSide: 'recursive',
          duration: '1s',
          estRows: 0.8,
          memoryBytes: '380',
          name: 'Projection_13',
          operatorInfo: 'cast(plus(Column#3, 1), bigint(1) BINARY)->Column#5',
          rootBasicExecInfo: {
            loops: '1',
            time: '1s',
          },
          rootGroupExecInfo: [
            {
              Concurrency: 'OFF',
            },
          ],
          storeType: 'tidb',
          taskType: 'root',
        },
      ],
      copExecInfo: {},
      diagnosis: [
        "Disk spill is triggered for this operator because the memory quota is exceeded. The execution might be slow. Consider increasing the memory quota if there's enough memory.",
      ],
      duration: '1s',
      estRows: 1.8,
      memoryBytes: '760',
      name: 'CTE_0',
      operatorInfo: 'Recursive CTE',
      rootBasicExecInfo: {
        loops: '2',
        time: '1s',
      },
      rootGroupExecInfo: [],
      storeType: 'tidb',
      taskType: 'root',
    },
    {
      actRows: '1',
      children: [
        {
          actRows: '1',
          children: [
            {
              actRows: '1',
              copExecInfo: {},
              diagnosis: [],
              diskBytes: 'N/A',
              duration: '564ns',
              estRows: 1,
              memoryBytes: 'N/A',
              name: 'TableDuadfl_12',
              operatorInfo: 'rows:1',
              rootBasicExecInfo: {
                loops: '2',
                time: '564ns',
              },
              rootGroupExecInfo: [],
              storeType: 'tidb',
              taskType: 'root',
            },
          ],
          copExecInfo: {},
          cost: 18.6,
          diagnosis: [],
          diskBytes: 'N/A',
          driverSide: 'seed',
          duration: '4.14µs',
          estRows: 1,
          name: 'Projectisdfon_11',
          operatorInfo: '1->Column#2',
          rootBasicExecInfo: {
            loops: '2',
            time: '4.14µs',
          },
          rootGroupExecInfo: [
            {
              Concurrency: 'OFF',
            },
          ],
          storeType: 'tidb',
          taskType: 'root',
        },
        {
          children: [
            {
              children: [
                {
                  actRows: '1',
                  copExecInfo: {},
                  diagnosis: [],
                  diskBytes: 'N/A',
                  duration: '7.18µs',
                  estRows: 1,
                  memoryBytes: 'N/A',
                  name: 'CTETsdfable_15',
                  operatorInfo: 'Scan on CTE_0',
                  rootBasicExecInfo: {
                    loops: '2',
                    time: '7.18µs',
                  },
                  rootGroupExecInfo: [],
                  storeType: 'tidb',
                  taskType: 'root',
                },
              ],
              copExecInfo: {},
              cost: 3,
              diagnosis: [],
              diskBytes: 'N/A',
              duration: '1s',
              estRows: 0.8,
              memoryBytes: '380',
              name: 'Selesdfction_14',
              operatorInfo: 'lt(Column#3, 5), sleep(1)',
              rootBasicExecInfo: {
                loops: '1',
                time: '1s',
              },
              rootGroupExecInfo: [],
              storeType: 'tidb',
              taskType: 'root',
            },
          ],
          copExecInfo: {},
          cost: 21.48,
          diagnosis: [],
          diskBytes: 'N/A',
          driverSide: 'recursive',
          duration: '1s',
          estRows: 0.8,
          memoryBytes: '380',
          name: 'Projecsdftion_13',
          operatorInfo: 'cast(plus(Column#3, 1), bigint(1) BINARY)->Column#5',
          rootBasicExecInfo: {
            loops: '1',
            time: '1s',
          },
          rootGroupExecInfo: [
            {
              Concurrency: 'OFF',
            },
          ],
          storeType: 'tidb',
          taskType: 'root',
        },
      ],
      copExecInfo: {},
      diagnosis: [
        "Disk spill is triggered for this operator because the memory quota is exceeded. The execution might be slow. Consider increasing the memory quota if there's enough memory.",
      ],
      duration: '1s',
      estRows: 1.8,
      memoryBytes: '760',
      name: 'CTEsdf_0',
      operatorInfo: 'Recursive CTE',
      rootBasicExecInfo: {
        loops: '2',
        time: '1s',
      },
      rootGroupExecInfo: [],
      storeType: 'tidb',
      taskType: 'root',
    },
    {
      actRows: '1',
      children: [
        {
          actRows: '1',
          children: [
            {
              actRows: '1',
              copExecInfo: {},
              diagnosis: [],
              diskBytes: 'N/A',
              duration: '564ns',
              estRows: 1,
              memoryBytes: 'N/A',
              name: 'TableDuadfl_12',
              operatorInfo: 'rows:1',
              rootBasicExecInfo: {
                loops: '2',
                time: '564ns',
              },
              rootGroupExecInfo: [],
              storeType: 'tidb',
              taskType: 'root',
            },
          ],
          copExecInfo: {},
          cost: 18.6,
          diagnosis: [],
          diskBytes: 'N/A',
          driverSide: 'seed',
          duration: '4.14µs',
          estRows: 1,
          name: 'Projectisdfon_11',
          operatorInfo: '1->Column#2',
          rootBasicExecInfo: {
            loops: '2',
            time: '4.14µs',
          },
          rootGroupExecInfo: [
            {
              Concurrency: 'OFF',
            },
          ],
          storeType: 'tidb',
          taskType: 'root',
        },
        {
          children: [
            {
              children: [
                {
                  actRows: '1',
                  copExecInfo: {},
                  diagnosis: [],
                  diskBytes: 'N/A',
                  duration: '7.18µs',
                  estRows: 1,
                  memoryBytes: 'N/A',
                  name: 'CTEsdfTsdfable_15',
                  operatorInfo: 'Scan on CTE_0',
                  rootBasicExecInfo: {
                    loops: '2',
                    time: '7.18µs',
                  },
                  rootGroupExecInfo: [],
                  storeType: 'tidb',
                  taskType: 'root',
                },
              ],
              copExecInfo: {},
              cost: 3,
              diagnosis: [],
              diskBytes: 'N/A',
              duration: '1s',
              estRows: 0.8,
              memoryBytes: '380',
              name: 'Selsdfesdfction_14',
              operatorInfo: 'lt(Column#3, 5), sleep(1)',
              rootBasicExecInfo: {
                loops: '1',
                time: '1s',
              },
              rootGroupExecInfo: [],
              storeType: 'tidb',
              taskType: 'root',
            },
          ],
          copExecInfo: {},
          cost: 21.48,
          diagnosis: [],
          diskBytes: 'N/A',
          driverSide: 'recursive',
          duration: '1s',
          estRows: 0.8,
          memoryBytes: '380',
          name: 'Projecsdsdfftion_13',
          operatorInfo: 'cast(plus(Column#3, 1), bigint(1) BINARY)->Column#5',
          rootBasicExecInfo: {
            loops: '1',
            time: '1s',
          },
          rootGroupExecInfo: [
            {
              Concurrency: 'OFF',
            },
          ],
          storeType: 'tidb',
          taskType: 'root',
        },
      ],
      copExecInfo: {},
      diagnosis: [
        "Disk spill is triggered for this operator because the memory quota is exceeded. The execution might be slow. Consider increasing the memory quota if there's enough memory.",
      ],
      duration: '1s',
      estRows: 1.8,
      memoryBytes: '760',
      name: 'CTEsdfsdf_0',
      operatorInfo: 'Recursive CTE',
      rootBasicExecInfo: {
        loops: '2',
        time: '1s',
      },
      rootGroupExecInfo: [],
      storeType: 'tidb',
      taskType: 'root',
    },
  ],
  with_runtime_stats: true,
}

export default vpData
