/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Cluster APIs for TiDB Cloud
 * OpenAPI spec version: alpha
 */
import type { ProtobufAny } from "./protobufAny"

export interface GooglerpcStatus {
  code?: number
  message?: string
  details?: ProtobufAny[]
}
