/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Cluster APIs for TiDB Cloud
 * OpenAPI spec version: alpha
 */

export interface ServerlessClusterAdviseIndexesReqPayload {
  /** The name of the database. */
  database_name: string
  /** Queries */
  queries: string[]
}
