/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Cluster APIs for TiDB Cloud
 * OpenAPI spec version: alpha
 */

export interface ServerlessIndexAdviceImpact {
  query?: string
  improvement?: number
}
