/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Cluster APIs for TiDB Cloud
 * OpenAPI spec version: alpha
 */
import type { BaseBaseRespTags } from "./baseBaseRespTags"

export interface BaseBaseResp {
  tags?: BaseBaseRespTags
  err_code?: string
  err_msg?: string
}
