/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Cluster APIs for TiDB Cloud
 * OpenAPI spec version: alpha
 */
import type { BaseBaseResp } from "./baseBaseResp"

export interface ServerlessClusterAdviseIndexesResp {
  /** The items of databases in the cluster. */
  text: string
  base_resp: BaseBaseResp
}
