/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Cluster APIs for TiDB Cloud
 * OpenAPI spec version: alpha
 */
import type { BaseBaseResp } from "./baseBaseResp"

export interface ServerlessClusterCreateDatabaseResp {
  base_resp: BaseBaseResp
}
