/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Cluster APIs for TiDB Cloud
 * OpenAPI spec version: alpha
 */
import type { ServerlessIndexAdviceImpact } from "./serverlessIndexAdviceImpact"

export interface ServerlessIndexAdvice {
  id?: string
  name?: string
  database?: string
  table?: string
  last_recommend_time?: string
  state?: string
  index_statement?: string
  improvement?: number
  index_size?: number
  reason?: string
  top_impacted_queries?: ServerlessIndexAdviceImpact[]
  state_reason?: string
  cost_saving_monthly?: number
  cost_saving_per_query?: number
}
