/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Example API
 * This is a Clinic server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { UserUserResp } from '../models';
/**
 * UserApi - axios parameter creator
 * @export
 */
export const UserApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * get profile
         * @summary Get profile
         * @param {string} xCsrfToken get value from login.ValidationResp response
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userProfileGet: async (xCsrfToken: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'xCsrfToken' is not null or undefined
            assertParamExists('userProfileGet', 'xCsrfToken', xCsrfToken)
            const localVarPath = `/user/profile`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (xCsrfToken !== undefined && xCsrfToken !== null) {
                localVarHeaderParameter['x-csrf-token'] = String(xCsrfToken);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserApi - functional programming interface
 * @export
 */
export const UserApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserApiAxiosParamCreator(configuration)
    return {
        /**
         * get profile
         * @summary Get profile
         * @param {string} xCsrfToken get value from login.ValidationResp response
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userProfileGet(xCsrfToken: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserUserResp>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.userProfileGet(xCsrfToken, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * UserApi - factory interface
 * @export
 */
export const UserApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserApiFp(configuration)
    return {
        /**
         * get profile
         * @summary Get profile
         * @param {string} xCsrfToken get value from login.ValidationResp response
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userProfileGet(xCsrfToken: string, options?: any): AxiosPromise<UserUserResp> {
            return localVarFp.userProfileGet(xCsrfToken, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for userProfileGet operation in UserApi.
 * @export
 * @interface UserApiUserProfileGetRequest
 */
export interface UserApiUserProfileGetRequest {
    /**
     * get value from login.ValidationResp response
     * @type {string}
     * @memberof UserApiUserProfileGet
     */
    readonly xCsrfToken: string
}

/**
 * UserApi - object-oriented interface
 * @export
 * @class UserApi
 * @extends {BaseAPI}
 */
export class UserApi extends BaseAPI {
    /**
     * get profile
     * @summary Get profile
     * @param {UserApiUserProfileGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public userProfileGet(requestParameters: UserApiUserProfileGetRequest, options?: AxiosRequestConfig) {
        return UserApiFp(this.configuration).userProfileGet(requestParameters.xCsrfToken, options).then((request) => request(this.axios, this.basePath));
    }
}
