/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Example API
 * This is a Clinic server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ClusterFileMeta
 */
export interface ClusterFileMeta {
    /**
     * 
     * @type {string}
     * @memberof ClusterFileMeta
     */
    'briefSize'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClusterFileMeta
     */
    'totalSize'?: string;
}

