/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Example API
 * This is a Clinic server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { DbTopology } from './db-topology';

/**
 * 
 * @export
 * @interface ClusterCluster
 */
export interface ClusterCluster {
    /**
     * 
     * @type {string}
     * @memberof ClusterCluster
     */
    'clusterType'?: string;
    /**
     * 
     * @type {number}
     * @memberof ClusterCluster
     */
    'created'?: number;
    /**
     * 
     * @type {number}
     * @memberof ClusterCluster
     */
    'dataSizeLimit'?: number;
    /**
     * Usage by the cluster in bytes
     * @type {number}
     * @memberof ClusterCluster
     */
    'dataSizeUsed'?: number;
    /**
     * 
     * @type {number}
     * @memberof ClusterCluster
     */
    'endTime'?: number;
    /**
     * 
     * @type {string}
     * @memberof ClusterCluster
     */
    'id'?: string;
    /**
     * 
     * @type {number}
     * @memberof ClusterCluster
     */
    'lastestUpdated'?: number;
    /**
     * 
     * @type {string}
     * @memberof ClusterCluster
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClusterCluster
     */
    'note'?: string;
    /**
     * 
     * @type {number}
     * @memberof ClusterCluster
     */
    'startTime'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ClusterCluster
     */
    'status'?: boolean;
    /**
     * 
     * @type {DbTopology}
     * @memberof ClusterCluster
     */
    'topology'?: DbTopology;
    /**
     * 
     * @type {number}
     * @memberof ClusterCluster
     */
    'totalOncall'?: number;
    /**
     * PackageCount int64 `json:\"package_count\"`
     * @type {number}
     * @memberof ClusterCluster
     */
    'totalReport'?: number;
    /**
     * 
     * @type {string}
     * @memberof ClusterCluster
     */
    'version'?: string;
}

