/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Example API
 * This is a Clinic server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ClusterUpdateClusterReq
 */
export interface ClusterUpdateClusterReq {
    /**
     * 
     * @type {string}
     * @memberof ClusterUpdateClusterReq
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClusterUpdateClusterReq
     */
    'name'?: string;
}

