/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Example API
 * This is a Clinic server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ClusterDataInfo } from './cluster-data-info';

/**
 * 
 * @export
 * @interface ClusterDataSummaryResponse
 */
export interface ClusterDataSummaryResponse {
    /**
     * 
     * @type {Array<ClusterDataInfo>}
     * @memberof ClusterDataSummaryResponse
     */
    'dataInfos'?: Array<ClusterDataInfo>;
    /**
     * 
     * @type {number}
     * @memberof ClusterDataSummaryResponse
     */
    'total'?: number;
}

