/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Example API
 * This is a Clinic server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ComputeEngineComparisonReportDataValues2 } from './compute-engine-comparison-report-data-values2';

/**
 * 
 * @export
 * @interface ComputeEngineComparisonReportDataComparisonTimeRange
 */
export interface ComputeEngineComparisonReportDataComparisonTimeRange {
    /**
     * 
     * @type {object}
     * @memberof ComputeEngineComparisonReportDataComparisonTimeRange
     */
    'subValues'?: object;
    /**
     * 
     * @type {ComputeEngineComparisonReportDataValues2}
     * @memberof ComputeEngineComparisonReportDataComparisonTimeRange
     */
    'values'?: ComputeEngineComparisonReportDataValues2;
}

