/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Example API
 * This is a Clinic server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ComputeEngineComparisonReportDataValues } from './compute-engine-comparison-report-data-values';

/**
 * 
 * @export
 * @interface ComputeEngineComparisonReportDataBusinessMetricsComparison
 */
export interface ComputeEngineComparisonReportDataBusinessMetricsComparison {
    /**
     * 
     * @type {object}
     * @memberof ComputeEngineComparisonReportDataBusinessMetricsComparison
     */
    'subValues'?: object;
    /**
     * 
     * @type {ComputeEngineComparisonReportDataValues}
     * @memberof ComputeEngineComparisonReportDataBusinessMetricsComparison
     */
    'values'?: ComputeEngineComparisonReportDataValues;
}

