/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Example API
 * This is a Clinic server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ComputeEngineComparisonReportArgs } from './compute-engine-comparison-report-args';
import { ComputeEngineComparisonReportData } from './compute-engine-comparison-report-data';

/**
 * 
 * @export
 * @interface ComputeEngineComparisonReport
 */
export interface ComputeEngineComparisonReport {
    /**
     * 
     * @type {ComputeEngineComparisonReportArgs}
     * @memberof ComputeEngineComparisonReport
     */
    'args'?: ComputeEngineComparisonReportArgs;
    /**
     * 
     * @type {number}
     * @memberof ComputeEngineComparisonReport
     */
    'created_at'?: number;
    /**
     * 
     * @type {ComputeEngineComparisonReportData}
     * @memberof ComputeEngineComparisonReport
     */
    'data'?: ComputeEngineComparisonReportData;
    /**
     * 
     * @type {string}
     * @memberof ComputeEngineComparisonReport
     */
    'hook'?: string;
    /**
     * 
     * @type {string}
     * @memberof ComputeEngineComparisonReport
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ComputeEngineComparisonReport
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ComputeEngineComparisonReport
     */
    'status'?: string;
    /**
     * 
     * @type {number}
     * @memberof ComputeEngineComparisonReport
     */
    'updated_at'?: number;
}

