/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Example API
 * This is a Clinic server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ComputeEngineComparisonReportDataValues2
 */
export interface ComputeEngineComparisonReportDataValues2 {
    /**
     * 
     * @type {number}
     * @memberof ComputeEngineComparisonReportDataValues2
     */
    't1EndTime'?: number;
    /**
     * 
     * @type {number}
     * @memberof ComputeEngineComparisonReportDataValues2
     */
    't1StartTime'?: number;
    /**
     * 
     * @type {number}
     * @memberof ComputeEngineComparisonReportDataValues2
     */
    't2EndTime'?: number;
    /**
     * 
     * @type {number}
     * @memberof ComputeEngineComparisonReportDataValues2
     */
    't2StartTime'?: number;
}

