/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Example API
 * This is a Clinic server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ComputeEngineComparisonReportDataValues3 } from './compute-engine-comparison-report-data-values3';

/**
 * 
 * @export
 * @interface ComputeEngineComparisonReportDataPerformanceMetricsComparison
 */
export interface ComputeEngineComparisonReportDataPerformanceMetricsComparison {
    /**
     * 
     * @type {object}
     * @memberof ComputeEngineComparisonReportDataPerformanceMetricsComparison
     */
    'subValues'?: object;
    /**
     * 
     * @type {ComputeEngineComparisonReportDataValues3}
     * @memberof ComputeEngineComparisonReportDataPerformanceMetricsComparison
     */
    'values'?: ComputeEngineComparisonReportDataValues3;
}

