/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Example API
 * This is a Clinic server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ComputeEngineComparisonReportDataValuesDescription } from './compute-engine-comparison-report-data-values-description';

/**
 * 
 * @export
 * @interface ComputeEngineComparisonReportDataValues3
 */
export interface ComputeEngineComparisonReportDataValues3 {
    /**
     * 
     * @type {string}
     * @memberof ComputeEngineComparisonReportDataValues3
     */
    'components'?: string;
    /**
     * 
     * @type {ComputeEngineComparisonReportDataValuesDescription}
     * @memberof ComputeEngineComparisonReportDataValues3
     */
    'description'?: ComputeEngineComparisonReportDataValuesDescription;
    /**
     * 
     * @type {object}
     * @memberof ComputeEngineComparisonReportDataValues3
     */
    'diff'?: object;
    /**
     * 
     * @type {string}
     * @memberof ComputeEngineComparisonReportDataValues3
     */
    'grafanaLocation'?: string;
    /**
     * 
     * @type {string}
     * @memberof ComputeEngineComparisonReportDataValues3
     */
    'label'?: string;
    /**
     * 
     * @type {string}
     * @memberof ComputeEngineComparisonReportDataValues3
     */
    'metrics'?: string;
    /**
     * 
     * @type {string}
     * @memberof ComputeEngineComparisonReportDataValues3
     */
    't1AverageValue'?: string;
    /**
     * 
     * @type {string}
     * @memberof ComputeEngineComparisonReportDataValues3
     */
    't2AverageValue'?: string;
}

