/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Example API
 * This is a Clinic server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LoginValidation
 */
export interface LoginValidation {
    /**
     * 
     * @type {string}
     * @memberof LoginValidation
     */
    'code'?: string;
    /**
     * 
     * @type {string}
     * @memberof LoginValidation
     */
    'redirect_uri'?: string;
    /**
     * 
     * @type {string}
     * @memberof LoginValidation
     */
    'state'?: string;
}

