/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Example API
 * This is a Clinic server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OrgApiKeyResponse
 */
export interface OrgApiKeyResponse {
    /**
     * 
     * @type {number}
     * @memberof OrgApiKeyResponse
     */
    'createdTime'?: number;
    /**
     * 
     * @type {number}
     * @memberof OrgApiKeyResponse
     */
    'id'?: number;
    /**
     * Name string `json:\"name\"`
     * @type {string}
     * @memberof OrgApiKeyResponse
     */
    'key'?: string;
}

