/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Example API
 * This is a Clinic server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { OrgUser } from './org-user';

/**
 * 
 * @export
 * @interface OrgListUsersResp
 */
export interface OrgListUsersResp {
    /**
     * 
     * @type {Array<OrgUser>}
     * @memberof OrgListUsersResp
     */
    'items'?: Array<OrgUser>;
    /**
     * 
     * @type {number}
     * @memberof OrgListUsersResp
     */
    'total'?: number;
}

