/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Example API
 * This is a Clinic server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OrgOrganization
 */
export interface OrgOrganization {
    /**
     * 
     * @type {number}
     * @memberof OrgOrganization
     */
    'clusterCount'?: number;
    /**
     * 
     * @type {string}
     * @memberof OrgOrganization
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrgOrganization
     */
    'externalID'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrgOrganization
     */
    'id'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof OrgOrganization
     */
    'isStarred'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof OrgOrganization
     */
    'lastUpdated'?: number;
    /**
     * 
     * @type {string}
     * @memberof OrgOrganization
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrgOrganization
     */
    'owner'?: string;
    /**
     * TODO: it should be in new api but UI hope to put in this response
     * @type {Array<string>}
     * @memberof OrgOrganization
     */
    'roleNames'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof OrgOrganization
     */
    'type'?: string;
}

