/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Example API
 * This is a Clinic server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { OrgApiKeyResponse } from './org-api-key-response';

/**
 * 
 * @export
 * @interface OrgListApiKeyResponse
 */
export interface OrgListApiKeyResponse {
    /**
     * 
     * @type {Array<OrgApiKeyResponse>}
     * @memberof OrgListApiKeyResponse
     */
    'items'?: Array<OrgApiKeyResponse>;
    /**
     * 
     * @type {number}
     * @memberof OrgListApiKeyResponse
     */
    'total'?: number;
}

