/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Example API
 * This is a Clinic server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OrgTaskStatus
 */
export interface OrgTaskStatus {
    /**
     * 
     * @type {string}
     * @memberof OrgTaskStatus
     */
    'name'?: string;
    /**
     * 
     * @type {number}
     * @memberof OrgTaskStatus
     */
    'process'?: number;
    /**
     * 
     * @type {number}
     * @memberof OrgTaskStatus
     */
    'size'?: number;
    /**
     * 
     * @type {string}
     * @memberof OrgTaskStatus
     */
    'taskType'?: string;
}

