/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Example API
 * This is a Clinic server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ReportHealthData } from './report-health-data';

/**
 * 
 * @export
 * @interface ReportHealthReport
 */
export interface ReportHealthReport {
    /**
     * 
     * @type {number}
     * @memberof ReportHealthReport
     */
    'endTime'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ReportHealthReport
     */
    'existed'?: boolean;
    /**
     * 
     * @type {ReportHealthData}
     * @memberof ReportHealthReport
     */
    'healthData'?: ReportHealthData;
    /**
     * 
     * @type {boolean}
     * @memberof ReportHealthReport
     */
    'inRebuild'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ReportHealthReport
     */
    'itemID'?: string;
    /**
     * 
     * @type {number}
     * @memberof ReportHealthReport
     */
    'progress'?: number;
    /**
     * 
     * @type {number}
     * @memberof ReportHealthReport
     */
    'startTime'?: number;
    /**
     * 
     * @type {string}
     * @memberof ReportHealthReport
     */
    'status'?: string;
}

