/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Example API
 * This is a Clinic server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ReportFeedbackArgs
 */
export interface ReportFeedbackArgs {
    /**
     * 
     * @type {boolean}
     * @memberof ReportFeedbackArgs
     */
    'agree'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ReportFeedbackArgs
     */
    'msg'?: string;
    /**
     * 
     * @type {number}
     * @memberof ReportFeedbackArgs
     */
    'rule'?: number;
    /**
     * 
     * @type {string}
     * @memberof ReportFeedbackArgs
     */
    'user'?: string;
}

