/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Example API
 * This is a Clinic server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { DbComparisonArg } from './db-comparison-arg';

/**
 * 
 * @export
 * @interface ReportComparisonReport
 */
export interface ReportComparisonReport {
    /**
     * 
     * @type {DbComparisonArg}
     * @memberof ReportComparisonReport
     */
    'args'?: DbComparisonArg;
    /**
     * 
     * @type {number}
     * @memberof ReportComparisonReport
     */
    'createdAt'?: number;
    /**
     * 
     * @type {string}
     * @memberof ReportComparisonReport
     */
    'creator'?: string;
    /**
     * 
     * @type {number}
     * @memberof ReportComparisonReport
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ReportComparisonReport
     */
    'status'?: string;
}

