/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Example API
 * This is a Clinic server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserUserResp
 */
export interface UserUserResp {
    /**
     * 
     * @type {number}
     * @memberof UserUserResp
     */
    'createdAt'?: number;
    /**
     * 
     * @type {string}
     * @memberof UserUserResp
     */
    'email'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserUserResp
     */
    'internal'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UserUserResp
     */
    'userName'?: string;
}

